/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.sql.*;
import java.util.ArrayList;
import java.util.Random;


import listadepalavras.Conexao;

/**
 *
 * @author Baby
 */
public class ImprimirPalavras extends javax.swing.JInternalFrame {

    private static ArrayList casamentoLista;
    private static ArrayList amorLista;
    private Conexao conetando;

    public void carregarPalavras() {

//        casamento.setText(" " + casamentoLista.get(aleatoria.nextInt(casamentoLista.size())));

  //      amor.setText("" + amorLista.get(aleatoria.nextInt(amorLista.size())));
    }

    static public class imprimir implements Runnable {

        private Random aleatoria= new Random();

        @Override
        public void run() {
            try {
                
                while (true) {
                
                    casamento.setText(" " + casamentoLista.get(aleatoria.nextInt(casamentoLista.size())));

                    amor.setText("" + amorLista.get(aleatoria.nextInt(amorLista.size())));
                    Thread.sleep(10000);
                }
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }

    }

    public void passar() {

        PreparedStatement psTm;
        ResultSet rSet;
        try {
            psTm = conetando.conn.prepareStatement("SELECT * FROM casamento ORDER BY id_casa");

            rSet = psTm.executeQuery();
            while (rSet.next()) {
                casamentoLista.add(rSet.getString("pal_cas"));
            }
            psTm = conetando.conn.prepareStatement("SELECT * FROM amor ORDER BY id_amor");

            rSet = psTm.executeQuery();
            while (rSet.next()) {
                amorLista.add(rSet.getString("pal_amor"));
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    public ImprimirPalavras() {
        initComponents();
        casamentoLista = new ArrayList();
        amorLista = new ArrayList();
        conetando = new Conexao();
        
        passar();
        carregarPalavras();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        casamento = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        amor = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setFocusCycleRoot(false);
        setFocusable(false);
        setRequestFocusEnabled(false);
        setVisible(true);

        jPanel1.setLayout(null);

        lab.setFont(new java.awt.Font("Victorian LET", 1, 36)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 255, 255));
        lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab.setText("CASAMENTO");
        jPanel1.add(lab);
        lab.setBounds(20, 10, 270, 40);

        jLabel4.setFont(new java.awt.Font("Victorian LET", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 29, 139));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AMOR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 10, 270, 40);

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        casamento.setEditable(false);
        casamento.setBackground(new java.awt.Color(102, 102, 102));
        casamento.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        casamento.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(casamento);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 40, 370, 190);

        amor.setEditable(false);
        amor.setBackground(new java.awt.Color(102, 102, 102));
        amor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amor.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        amor.setForeground(new java.awt.Color(255, 19, 162));
        amor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(amor);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(370, 40, 400, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CachedImage_1440_900_POS4.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-60, -220, 970, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        setBounds(0, 0, 788, 257);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextPane amor;
    private static javax.swing.JTextPane casamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lab;
    // End of variables declaration//GEN-END:variables
}
