/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import control.Funcao;
import control.Sintaxe;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author MR-STUDIOS
 */
public class Principal extends javax.swing.JFrame {

    private Sintaxe sita;

    public Principal() {
        initComponents();
        escreverNu();
        escreverSIm();
        sita = new Sintaxe();
    }

    private String removeCaracters(int pos) {
        String entrada = equac.getText();
        String saida = "";

        try {

            if (Character.isDigit(entrada.charAt(entrada.length() - 1))
                    || Character.isMirrored(entrada.charAt(entrada.length() - 1))
                    || entrada.charAt(entrada.length() - 1) == '.'
                    || entrada.charAt(entrada.length() - 1) == '+'
                    || entrada.charAt(entrada.length() - 1) == '-'
                    || entrada.charAt(entrada.length() - 1) == '*'
                    || entrada.charAt(entrada.length() - 1) == '/'
                    || entrada.charAt(entrada.length() - 1) == '!'
                    || entrada.charAt(entrada.length() - 1) == '^'
                    || entrada.charAt(entrada.length() - 1) == '%') {

                saida = entrada;
            } else {
                saida = entrada.substring(0, entrada.length() - 1);
            }
        } catch (StringIndexOutOfBoundsException ex) {
            saida = entrada.substring(0, entrada.length());

        }
        return saida;

    }

    private void escreverNu() {
        for (Component meu : pOper.getComponents()) {
            JButton passar = (JButton) meu;
            passar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String equaca = equac.getText();
                    if (!passar.getText().equals("=") && !passar.getText().equals("AC")
                            && !passar.getText().equals("C")) {
                        equac.setText(equac.getText() + passar.getName());
                    } else if (passar.getText().equals("=")) {
                        result.setText("0");
                        result.setForeground(Color.BLACK);
                        if (sita.verSin(equaca)) {
                            result.setText(sita.extrair(equaca));
                        } else {
                            result.setText("ERRO DE SINTAXE!");
                            result.setForeground(Color.red);
                        }
                    } else if (passar.getText().equals("C")) {
                        eliminar();
                    }
                }
            });

        }
    }

    private void constante(char simb) {
        Funcao fac=new Funcao();
        String entrada = equac.getText();
        
        String numero = "";
        int i = entrada.length()-2;
        while (Character.isDigit(entrada.charAt(i))) {
            
            numero += entrada.charAt(i);
            if (i == 0) {
                break;
            }
            i--;
        }
        if(simb=='!'){
              result.setText(""+ fac.fact(Integer.parseInt(numero)));
        }
    }

    private void escreverSIm() {
        for (Component meu : pTecl.getComponents()) {
            JButton passar = (JButton) meu;
            passar.addActionListener((java.awt.event.ActionEvent evt) -> {
                if (!passar.getText().equals("!")) {
                    equac.setText(equac.getText() + passar.getText());
                } else if (passar.getText().equals("!")) {
                     equac.setText(equac.getText() + passar.getText());
                    constante('!');
                }
            });

        }
    }


    private void eliminar() {
        if (equac.getText().length() > 0) {
            String pas = "";
            int pos = equac.getCaretPosition();
            for (int i = 0; i < equac.getText().length(); i++) {

                if (i == pos - 1) {
                    continue;
                }
                pas += equac.getText().toCharArray()[i];
            }

            equac.setText(pas);
            equac.setCaretPosition(pos - 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        equac = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        pTecl = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        pOper = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setMaximumSize(new java.awt.Dimension(343, 255));
        setMinimumSize(new java.awt.Dimension(343, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(343, 255));

        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        equac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                equacKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                equacKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                equacKeyPressed(evt);
            }
        });
        jPanel2.add(equac);
        equac.setBounds(0, 0, 380, 30);

        result.setEditable(false);
        result.setText("0");
        result.setFocusable(false);
        result.setRequestFocusEnabled(false);
        jPanel2.add(result);
        result.setBounds(0, 30, 380, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 70);

        jPanel3.setLayout(null);

        pTecl.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("9");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setFocusable(false);
        pTecl.add(jButton2);
        jButton2.setBounds(100, 10, 50, 40);

        jButton22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton22.setText("7");
        jButton22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton22.setFocusable(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        pTecl.add(jButton22);
        jButton22.setBounds(0, 10, 50, 40);

        jButton23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton23.setText("4");
        jButton23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton23.setFocusable(false);
        pTecl.add(jButton23);
        jButton23.setBounds(0, 50, 50, 40);

        jButton24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton24.setText("5");
        jButton24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton24.setFocusable(false);
        pTecl.add(jButton24);
        jButton24.setBounds(50, 50, 50, 40);

        jButton25.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton25.setText("6");
        jButton25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton25.setFocusable(false);
        pTecl.add(jButton25);
        jButton25.setBounds(100, 50, 50, 40);

        jButton26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton26.setText("1");
        jButton26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton26.setFocusable(false);
        pTecl.add(jButton26);
        jButton26.setBounds(0, 90, 50, 40);

        jButton27.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton27.setText("2");
        jButton27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton27.setFocusable(false);
        pTecl.add(jButton27);
        jButton27.setBounds(50, 90, 50, 40);

        jButton28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton28.setText("3");
        jButton28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton28.setFocusable(false);
        pTecl.add(jButton28);
        jButton28.setBounds(100, 90, 50, 40);

        jButton29.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton29.setText(".");
        jButton29.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton29.setFocusable(false);
        pTecl.add(jButton29);
        jButton29.setBounds(0, 130, 50, 40);

        jButton30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton30.setText("0");
        jButton30.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton30.setFocusable(false);
        pTecl.add(jButton30);
        jButton30.setBounds(50, 130, 50, 40);

        jButton31.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton31.setText("!");
        jButton31.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton31.setFocusable(false);
        pTecl.add(jButton31);
        jButton31.setBounds(100, 130, 50, 40);

        jButton32.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton32.setText("8");
        jButton32.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton32.setFocusable(false);
        pTecl.add(jButton32);
        jButton32.setBounds(50, 10, 50, 40);

        jPanel3.add(pTecl);
        pTecl.setBounds(0, 0, 150, 180);

        pOper.setLayout(null);

        jButton1.setText("n^x");
        jButton1.setFocusable(false);
        jButton1.setName("^"); // NOI18N
        pOper.add(jButton1);
        jButton1.setBounds(110, 70, 70, 30);

        jButton11.setText("+");
        jButton11.setFocusable(false);
        jButton11.setName("+"); // NOI18N
        pOper.add(jButton11);
        jButton11.setBounds(0, 0, 40, 40);

        jButton12.setText("-");
        jButton12.setFocusable(false);
        jButton12.setName("-"); // NOI18N
        pOper.add(jButton12);
        jButton12.setBounds(0, 40, 40, 30);

        jButton13.setText("sin(x)");
        jButton13.setFocusable(false);
        jButton13.setName("sin()"); // NOI18N
        pOper.add(jButton13);
        jButton13.setBounds(40, 40, 70, 30);

        jButton14.setText("( )");
        jButton14.setFocusable(false);
        jButton14.setName("()"); // NOI18N
        pOper.add(jButton14);
        jButton14.setBounds(110, 130, 70, 30);

        jButton15.setText("*");
        jButton15.setFocusable(false);
        jButton15.setName("*"); // NOI18N
        pOper.add(jButton15);
        jButton15.setBounds(0, 70, 40, 30);

        jButton16.setText("cos(x)");
        jButton16.setFocusable(false);
        jButton16.setName("cos()"); // NOI18N
        pOper.add(jButton16);
        jButton16.setBounds(40, 70, 70, 30);

        jButton17.setText("π");
        jButton17.setFocusable(false);
        jButton17.setName("π"); // NOI18N
        pOper.add(jButton17);
        jButton17.setBounds(0, 130, 40, 30);

        jButton18.setText("/");
        jButton18.setFocusable(false);
        jButton18.setName("/"); // NOI18N
        pOper.add(jButton18);
        jButton18.setBounds(0, 100, 40, 30);

        jButton19.setText("√x");
        jButton19.setFocusable(false);
        jButton19.setName("√()"); // NOI18N
        pOper.add(jButton19);
        jButton19.setBounds(40, 100, 70, 30);

        jButton20.setText("%");
        jButton20.setFocusable(false);
        jButton20.setName("%"); // NOI18N
        pOper.add(jButton20);
        jButton20.setBounds(40, 130, 70, 30);

        jButton21.setText("AC");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        pOper.add(jButton21);
        jButton21.setBounds(40, 0, 70, 40);

        jButton3.setText("e");
        jButton3.setFocusable(false);
        jButton3.setName("e"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pOper.add(jButton3);
        jButton3.setBounds(110, 100, 70, 30);

        jButton4.setText("C");
        jButton4.setFocusable(false);
        pOper.add(jButton4);
        jButton4.setBounds(110, 0, 70, 40);

        jButton5.setText("mod(x)");
        jButton5.setFocusable(false);
        jButton5.setName("mod()"); // NOI18N
        pOper.add(jButton5);
        jButton5.setBounds(110, 40, 70, 30);

        jButton33.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton33.setText("=");
        jButton33.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton33.setFocusable(false);
        pOper.add(jButton33);
        jButton33.setBounds(180, 0, 50, 160);

        jPanel3.add(pOper);
        pOper.setBounds(150, 10, 230, 180);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 80, 380, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        //limpar

        equac.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void equacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_equacKeyPressed
        if (evt.getKeyCode() >= 37 && evt.getKeyCode() <= 40) {

        } else {
            equac.setText(removeCaracters(equac.getCaretPosition()));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_equacKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField equac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pOper;
    private javax.swing.JPanel pTecl;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
